openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080/holidays
    description: Main (production) server
  - url: http://localhost:8080
    description: internal staging server for testing
paths:
  /holidays:
    get:
      summary: Returns a list of holidays.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of holidays
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
