openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080/national_holidays_team_project_war/
    description: Main (production) server
  - url: http://localhost:8080
    description: internal staging server for testing
paths:
  /allHolidays:
    get:
      summary: Returns a JSON list of holidays.
      description: Optional extended description in CommonMark or HTML.
      responses:

        '200':    # status code
          description: A JSON array of holidays
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
                  required:
                    - id
                    - name
                    - date
                  properties:
                    id:
                      type: integer
                    date:
                      type: object
                      properties:
                        year: integer
                        month: integer
                        day: integer
                    name:
                      type: string
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /holidaysById/{id}:
    get:
      summary: Returns a JSON of the holiday when found by unique id
      description:
      responses:

        '200':    # status code
          description: A JSON file containing a holiday
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                  - date
                properties:
                  id:
                    type: integer
                  date:
                    type: object
                    properties:
                      year: integer
                      month: integer
                      day: integer
                  name:
                    type: string

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /holidaysByDate/{month}/{day}:
    get:
      summary: Returns a JSON of the holiday when found by date
      description:
      responses:

        '200':    # status code
          description: A JSON file containing a holiday
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                  - date
                properties:
                  id:
                    type: integer
                  date:
                    type: object
                    properties:
                      year: integer
                      month: integer
                      day: integer
                  name:
                    type: string

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /holidaysByName/{name}:
    get:
      summary: Returns a JSON of the holiday when found by name
      description:
      responses:

        '200':    # status code
          description: A JSON file containing a holiday
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - name
                  - date
                properties:
                  id:
                    type: integer
                  date:
                    type: object
                    properties:
                      year: integer
                      month: integer
                      day: integer
                  name:
                    type: string

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string