openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://localhost:8080/national_holidays_team_project_war/
    description: Main (production) server
  - url: http://localhost:8080
    description: internal staging server for testing
paths:
  /services/holidays/all:
    get:
      summary: Returns a JSON list of holidays.
      description: Optional extended description in CommonMark or HTML.
      responses:

        '200':    # status code
          description: A JSON array of holidays
          content:
            application/json:
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Holiday'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /id/{id}:
    get:
      summary: Returns a JSON of the holiday when found by unique id
      description:
      responses:

        '200':    # status code
          description: A JSON file containing a holiday
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holiday'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /dates/{month}/{day}:
    get:
      summary: Returns a JSON of the holiday when found by date
      description:
      responses:

        '200':    # status code
          description: A JSON file containing a holiday
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holiday'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /names/{name}:
    get:
      summary: Returns a JSON of the holiday when found by name
      description:
      responses:

        '200':    # status code
          description: A JSON file containing a holiday
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holiday'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /daily:
    get:
      summary: Returns a JSON of the holidays for today
      description:
      responses:

        '200':    # status code
          description: A JSON file containing holidays
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Holiday'

        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /update:
    post:
      summary: Returns a JSON of the updated holiday
      description:
      operationId: updateHoliday
      parameters:
        - name: id
          in: path
          description: ID of holiday to be updated
          required: true
          schema:
            type: integer
        - name: name
          in: path
          description: new name of holiday
          required: true
          schema:
            type: string
        - name: date
          in: path
          description: new date of holiday
          required: true
          schema:
            type: string
      responses:

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /add:
    post:
      summary: Returns a JSON of the new holiday
      description:
      operationId: addHoliday
      parameters:
        - name: month
          in: query
          description: month of holiday to be added
          required: true
          schema:
            type: integer
        - name: day
          in: query
          description: day of holiday to be added
          required: true
          schema:
            type: integer
        - name: name
          in: query
          description: name of holiday to be added
          required: true
          schema:
            type: string
      responses:

        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


components:
  schemas:
    Holiday:
      required:
        - id
        - name
        - date
      properties:
        id:
          type: integer
          example: 1
        date:
          type: object
          properties:
            year: integer
            month: integer
            day: integer
        name:
          type: string
          example: Bring your daughter to work day
